node{

    stage("拉取代码"){
      echo "拉取代码"
    }
    stage("编译打包"){
      echo "编译打包"
        // groovy语法
        try{
            
        }
        catch(err){
            // 异常处理代码
        }
    }
    stage("部署"){
      echo "部署"
    }
}

